{{- if not .Values.sealed_secrets.enabled }}
{{- if .Values.managed_redis.disabled }}
{{- if eq .Values.redis.enabled true -}}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-password: '{.data[''database-password'']}'
  labels:
    {{- include "redis.labels" . | nindent 4 }}
  name: {{ template "redis.name" . }}
stringData:
  database-password: {{ .Values.redis.redis_password }}
{{- end }}
{{- end }}
{{- end }}