{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "redis.fullname" . }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
    - name: redis
      port: {{ .Values.service.port | default "6379" }}
      protocol: TCP
      targetPort: {{ .Values.service.port | default "6379" }}
  selector:
    app: {{ .Chart.Name }}
    deploymentconfig: {{ template "redis.fullname" . }}
  sessionAffinity: None
  type: {{ .Values.service.type | default "ClusterIP" }}
{{- end }}
