{{- if .Values.enabled }}
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: backup-container-builder
spec:
  completionDeadlineSeconds: 600
  failedBuildsHistoryLimit: 3
  source: 
  {{- toYaml .Values.buildconfig.source | nindent 4 }}
  strategy: 
  {{- toYaml .Values.buildconfig.strategy | nindent 4 }}
  output:
    to:
      kind: "ImageStreamTag"
      name: "backup-runner:latest"
{{- end }}