{{- if .Values.enabled }}
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: backup-container-builder
  labels:
    app: {{ template "backup-runner.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  triggers: []
  completionDeadlineSeconds: 600
  failedBuildsHistoryLimit: 3
  source: 
  {{- toYaml .Values.buildconfig.source | nindent 4 }}
  strategy: 
  {{- toYaml .Values.buildconfig.strategy | nindent 4 }}
  output:
    to:
      kind: "ImageStreamTag"
      name: "backup-runner:latest"
{{- end }}
