{{- if .Values.enabled }}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  generation: 1
  name: backup-runner
  labels:
    app: {{ template "backup-runner.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    generation: 1
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
{{- end }}