{{- if .Values.sealed_secrets }}
{{- range .Values.sealed_secrets }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ .name }}
spec:
  encryptedData:
  {{- range $key, $val := .encryptedData }}
    {{ $key }}: {{ $val }}
  {{- end }}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: {{ .name }}
{{ end }}
{{ end }}
