{{- if .Values.sealed_secrets }}
{{- range .Values.sealed_secrets }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .name }}
spec:
  encryptedData:
  {{- range $key, $val := .encryptedData }}
    {{ $key }}: {{ $val }}
  {{- end }}
  template:
    metadata:
      name: {{ .name }}
{{ end }}
{{ end }}